### ISSUE TITLE
feat: Make the first commit for the repo `trustful-zuzalu-contracts`

### ISSUE THREAD

**Issue by RafaDSan** [blockful-io/trustful-zuzalu-contracts#2]
- [x] Create new repo `trustful-zuzalu-contracts`
- [x] Make its first commit

**Comment by RafaDSan** [comment]
Repository created [here](https://github.com/blockful-io/trustful-zuzalu-contracts)
First commit [here](https://github.com/blockful-io/trustful-zuzalu-contracts/commit/522ba1839f56096b6b3dd1cb2dc2ced90732eabb)

**Comment by 0xneves** [comment]
Reopening this issue to migrate from hardhat to foundry.

**Comment by 0xneves** [comment]
closed by #3
